name: GitHub-Profile-Summary-Cards

on:
  schedule: # بتشتغل كل يوم الساعة 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # بتسمح لك تشغلها يدوياً في أي وقت

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24f1111/github-profile-summary-cards@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME_NAME: nord_dark # اسم الثيم اللي يعجبك
