name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # بتشتغل تلقائياً كل يوم الساعة 12 بالليل UTC
  workflow_dispatch: # بتسمح لك تشغلها يدوياً في أي وقت من قائمة Actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write # إعطاء صلاحيات الكربت للكتابة ورفع الصور للـ Repo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: GitHub-Profile-Summary-Cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME_NAME: nord_dark
          UTC_OFFSET: 2 # التوقيت المحلي كمثال (UTC+2)
